### ISSUE TITLE
[ISSUE] Oxygen Gear and Thermal Padding getting reset after re-joining a world/server

### ISSUE THREAD

**Issue by knoxhack** [ReadOnly-Mods/GalacticTweaks#2]
#### Issue Description:  
When re-joining a world/server the oxygen gear and thermal padding inventory gets reset to default deleting any new tanks or padding that the player has added

#### What happens:
Before leaving a world:
![2020-08-14_10 49 37](https://user-images.githubusercontent.com/9358725/90263178-4ae28b00-de1d-11ea-86a2-ed87cff03688.png)

After leaving a world:
![2020-08-14_10 50 05](https://user-images.githubusercontent.com/9358725/90263198-52099900-de1d-11ea-99ab-2ea0f9c43c73.png)

#### Important Versions Info (Do *not* use "latest"):
- Modpack: Astroblock 2 (Not out yet)
- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- GalacticTweaks: GalacticTweaks-1.0.0
- Galacticraft: GalacticraftCore-1.12.2-4.0.2.280
- Using a server (yes/no): Yes
  - If yes, are any Server API's used, what version? (ex: Sponge): No
- List any Galacticraft Addons w/ versions:
 - Addons:
GalacticraftTweaker-1.12.2-1.0.3
GalaxySpace-1.12.2-2.0.14
PlanetProgression-1.12.2-0.4.4

#### Your most recent log file where the issue was present: 
[https://gist.github.com/knoxhack/71e671cffde8dd59ea689fc9883a40e2](https://gist.github.com/knoxhack/71e671cffde8dd59ea689fc9883a40e2)

**Comment by ROMVoid95** [comment]
Ill get this fixed asap

**Comment by knoxhack** [comment]
Thanks 😊

**Comment by ROMVoid95** [comment]
Not a problem thanks for pointing that out

the updated version is now avilable
https://www.curseforge.com/minecraft/mc-mods/galactictweaks/files/3032603
