### ISSUE TITLE
[FEATURE] Advanced Rocketry Compatiblity

### ISSUE THREAD

**Issue by Gandalf360one** [ReadOnly-Mods/GalacticTweaks#22]
## Feature Request
[ Pls make the "oxygentoggle" option compatible with Advanced Rocketry so the oxygen system from Galacticraft can be used.
I tried using it but it doesnt work when I want to blacklist the space station dimesnion as oxygen dimension.  ]</br>

### What feature or addition are you suggesting?
[ This option should be compatible with advanced rocketry too so the oxygen system from galacticraft does also work in that dimesnion. ]</br>

### Feature request reason
[ I would make Galacticraf and Advanced Rocketry eaven more compatible to each other when you use it in combination. ]</br>

### Feature request dependencies
[  Would require compatiblity to Advanced Rocketry ]</br>
[ Advanced Rocketry ]

**Comment by ROMVoid95** [comment]
This falls outside of the mods scope, GalacticTweaks is an addon to Galacticraft and will only contain tweaks/fixes that interact with Galacticraft and any addons only.
