### ISSUE TITLE
[ISSUE] Mod is unavailable on Third-party Launchers

### ISSUE THREAD

**Issue by DDriggs00** [ReadOnly-Mods/GalacticTweaks#24]
## Issue Report (Not for Crashes - Please use Crash Report template for crashes)
</br>

You have the Curseforge "Prevent Third-Party Distribution" setting enabled, which prevents your mod from being used on third-party launchers. Many people do not want to use the Overwolf launcher due to privacy and data-harvesting concerns, or inaccessibility on Linux, and this restriction makes it difficult for those people to use modpacks with your mod in them, as well as discouraging pack developers from including your mod. Additionally, it makes it much more difficult to host a server with this mod. For more details, see https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

#### What happens:
The Mod is inaccessible from non-overwolf launchers

#### What you expected to happen:
The Mod to be accessible from non-overwolf launchers

#### Important Versions Info (Do *not* use "latest"):

- Minecraft: N/A
- Forge: N/A
- GalacticTweaks: N/A
- Galacticraft: N/A
- Using a server (yes/no): N/A
  - If yes, are any Server API's used, what version? (ex: Sponge): 
- List any Galacticraft Addons w/ versions:
 - Addons:

#### Your most recent log file where the issue was present: 

N/A

**Comment by ROMVoid95** [comment]
https://modrinth.com/mod/galactictweaks

these are the platforms the mod is available from. This will not change nor will I be adjusting the availability because of an obscure random rant from someone i don't know. This isn't said or meant to come off as rude or anything like that just more direct on the request.
