### ISSUE TITLE
Extra planets to new galaxy

### ISSUE THREAD

**Issue by mMONTAGEe** [ReadOnly-Mods/GalacticTweaks#3]
## Issue Report (Not for Crashes - Please use Crash Report template for crashes)
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ #### Important:
 - If you decide to delete this template entirely, your issue will be closed. 
 - If you do not provide relevant information when reporting an issue (for example experiencing a bug or glitch and not providing your  latest.log or relevant log) this issue will be closed.
### Please use [This Haste Server](https://haste.romvoid.dev) to paste ANY logs as these are set to never expire. ]

[ #### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. 
If you are using an unofficial version of GalacticTweaks please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate. ]

#### What happens:
In config there was a function. to move dublicated planets from ExtraPlanets to *Wormhole*.
After moving them to *Wormhole* The solar system in Milky Way got lost. Only earth mars and Venus.  and some Dwarf planets from EP.

#### What you expected to happen:
GS Solar system in Milky Way and EP solar system in *Wormhole*

#### Important Versions Info (Do *not* use "latest"):

- Minecraft: 1.12.2 
- Forge:14.23.5.2854
- GalacticTweaks: 1.0.0
- Galacticraft:4.0.2.280
- Using a server (yes/no): no
  - If yes, are any Server API's used, what version? (ex: Sponge): 
- List any Galacticraft Addons w/ versions:
 - Addons:More Planets, Extra Planets, Galaxy Space.

#### Your most recent log file where the issue was present: 
https://haste.romvoid.dev/kupoluxake.md

[ haste.romvoid.dev link here ]

**Comment by ROMVoid95** [comment]
was the config file for the mod deleted after updating?

**Comment by mMONTAGEe** [comment]
I need to update the config?

**Comment by ROMVoid95** [comment]
The changelog states to delete the mods config before updating
